server:
  port: 8090

spring:
  application:
    name: retry-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: RETRY_GROUP
        metadata:
          version: "1.0.0"
