server:
  port: 8081

spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: CORE_GROUP
        metadata:
          version: "1.0.0"
