server:
  port: 8094

spring:
  application:
    name: bulkhead-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: GOVERNANCE_GROUP
